name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening an issue. We welcome your contribution in maintaining the repo!!'
        pr-message: 'Thank you for your contribution as a new contributor!!'
